# Harmony Jekyll theme general configurations

# Site live URL
url: https://dvj.me.uk

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Dave Jones
  # Little description about your site
  description: My Place On The Net
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
   Hi, I'm Dave, a 20-something tech enthusiast based in Edinburgh, Scotland.
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Dave Jones
    email: david@dvj.me.uk
    url: dvj.me.uk

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social:
    github: dvjones89
    twitter: dvjones89
    facebook:
    gplus:
    dribble:
    pinterest:

# Conversion / Build settings
markdown:    kramdown
highlighter: rouge

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
